### ISSUE TITLE
I can't shrinkwrap my falafel.

### ISSUE THREAD

**Issue by bobthecow** [substack/node-falafel#28]
falafel's keeping me from npm-shrinkwrapping:

```
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: esprima@1.1.0-dev /Users/justin/Projects/four53/presentate/node_modules/debowerify/node_modules/falafel/node_modules/esprima
npm ERR!     at shrinkwrap_ (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/lib/shrinkwrap.js:29:15)
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/lib/shrinkwrap.js:23:5
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/lib/ls.js:43:30
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/justin/Projects/four53/presentate
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
```

It appears to be because `package.json` declares `esprima` as a bundled dependency, but doesn't declare it as a dependency. If I add this to falafel's `package.json`, everything works:

```json
{
  "dependencies": {"esprima": "1.1.0-dev"}
}
```

**Comment by substack** [comment]
No longer a problem in 1.0.0.

**Comment by leedm777** [comment]
FWIW, this was because falafel 0.3.1 had that version of esprima bundled in its `node_modules` directory.

```
$ tar tzf ~/.npm/falafel/0.3.1/package.tgz | grep esprima
package/node_modules/esprima/package.json
package/node_modules/esprima/.npmignore
package/node_modules/esprima/README.md
package/node_modules/esprima/esprima.js
package/node_modules/esprima/bin/esparse.js
package/node_modules/esprima/bin/esvalidate.js
package/node_modules/esprima/component.json
package/node_modules/esprima/ChangeLog
package/node_modules/esprima/LICENSE.BSD
package/node_modules/esprima/examples/detectnestedternary.js
package/node_modules/esprima/examples/findbooleantrap.js
package/node_modules/esprima/examples/tokendist.js
package/node_modules/esprima/index.html
package/node_modules/esprima/test/test.js
package/node_modules/esprima/test/compare.js
package/node_modules/esprima/test/compat.js
package/node_modules/esprima/test/benchmarks.js
package/node_modules/esprima/test/module.js
package/node_modules/esprima/test/reflect.js
package/node_modules/esprima/test/run.js
package/node_modules/esprima/test/runner.js
package/node_modules/esprima/test/index.html
package/node_modules/esprima/test/module.html
package/node_modules/esprima/test/compat.html
package/node_modules/esprima/test/compare.html
package/node_modules/esprima/test/coverage.html
package/node_modules/esprima/test/benchmarks.html
package/node_modules/esprima/test/esprima.js.html
package/node_modules/esprima/doc/index.html
```

**Comment by bobthecow** [comment]
@leedm777 yep. see https://github.com/bobthecow/node-falafel/commit/a858ea5585b135cbdb514b3be1a6aafbc256f59f
